### PR TITLE
fix autoplay parameter

### PR DESCRIPTION
**Pull request by marcari**
Hi Mathieu,

Could you please merge and release a new vecc?

thanks.

### CODE REVIEW

**Comment by magopian** [comment]
Hi @marcari,

i've also added you to the list of collaborators ;)

**Comment by magopian** [comment]
I've just released version 0.13 on pypi

**Comment by marcari** [comment]
Thanks! You're so fast! :+1:

**Comment by magopian** [comment]
Except when I'm supposed to do some overhaul work on vecc to make it use APIs instead of dumb GET/HEAD that are now blocked by many providers :(

I'm sorry I can't find the motivation to do this, I feel like I'm letting you down.

**Pull request merged**
